name: pywtype
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - cartopy
  - doc8
  - eofs
  - ipython
  - matplotlib
  - mypy
  - netCDF4
  - numba
  - pandas
  - pylint
  - pytest
  - scikit-learn
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - xarray