name: pywtype
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - jupyter
  - matplotlib
  - mypy
  - netCDF4
  - pylint
  - pytest
  - scikit-learn
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - xarray